apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: playground-web-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "playground-ai"

    networking.gke.io/managed-certificates: "playground-web-certificate"
    kubernetes.io/ingress.allow-http: "false"
spec:
  defaultBackend:
    service:
      name: playground-web-service
      port:
        number: 80