apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
  - name: us-east1-docker.pkg.dev/playground-ai-478208/playground/web-app
    newTag: TAG # This 'TAG' placeholder will be replaced by the GITHUB_SHA

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - managed-certificates.yaml
  - backend-config.yaml