# This workflow build and push a Docker container to Google Artifact Registry
# and deploy it on Cloud Run when a commit is pushed to the "main"
# branch.
#
# To configure this workflow:
#
# 1. Enable the following Google Cloud APIs:
#
#    - Artifact Registry (artifactregistry.googleapis.com)
#    - Cloud Run (run.googleapis.com)
#    - IAM Credentials API (iamcredentials.googleapis.com)
#
#    You can learn more about enabling APIs at
#    https://support.google.com/googleapi/answer/6158841.
#
# 2. Create and configure a Workload Identity Provider for GitHub:
#    https://github.com/google-github-actions/auth#preferred-direct-workload-identity-federation.
#
#    Depending on how you authenticate, you will need to grant an IAM principal
#    permissions on Google Cloud:
#
#    - Artifact Registry Administrator (roles/artifactregistry.admin)
#    - Cloud Run Developer (roles/run.developer)
#
#    You can learn more about setting IAM permissions at
#    https://cloud.google.com/iam/docs/manage-access-other-resources
#
# 3. Change the values in the "env" block to match your values.

name: 'Build and Deploy to Cloud Run'

on:
  push:
    branches:
      - Deployment
  pull_request:
    branches:
      - Deployment

env:
  PROJECT_ID: "playground-ai-478208" # Replace with your project ID
  REGION: "us-east1"
  APP_NAME: "playground-global"
  WIF_PROVIDER: "projects/817349898318/locations/global/workloadIdentityPools/playground-ai-github/providers/t-mcleod-github-provider"
  WIF_SERVICE_ACCOUNT: "service-account-1@playground-ai-478208.iam.gserviceaccount.com"


jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'

    name: 'Build and Push'
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.image-info.outputs.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - name: Docker Auth
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        id: image-info
        run: |
          TAG="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.APP_NAME }}-backend-repo/playground-backend:${{ github.sha }}"
          docker build -t $TAG .
          echo "tag=$TAG" >> $GITHUB_OUTPUT

  test:
    name: 'Automated Testing'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Run Placeholder Tests
        run: |
          echo "No tests configured yet. Skipping..."
          exit 0

  deploy:
    name: 'Terraform Deploy'
    needs: [build, test] # Wait for build to finish and tests to pass
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.WIF_PROVIDER }}
          service_account: ${{ env.WIF_SERVICE_ACCOUNT }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./terraform
      
      - name: Terraform Apply (Registry Only)
        run: terraform apply "-target=module.compute.google_artifact_registry_repository.playground-tf-repo" -auto-approve
        working-directory: ./terraform

      - name: Docker Auth & Push
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          docker build -t ${{ needs.build.outputs.image_tag }} .
          docker push ${{ needs.build.outputs.image_tag }}

      - name: Terraform Apply
        run: terraform apply -var="image_tag=${{ needs.build.outputs.image_tag }}" -auto-approve
        working-directory: ./terraform

  # deploy:
  #   runs-on: 'ubuntu-latest'

  #   permissions:
  #     contents: 'read'
  #     id-token: 'write'

  #   steps:
  #     - name: 'Checkout'
  #       uses: 'actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332' # actions/checkout@v4

  #     # Configure Workload Identity Federation and generate an access token.
  #     #
  #     # See https://github.com/google-github-actions/auth for more options,
  #     # including authenticating via a JSON credentials file.
  #     - id: 'auth'
  #       name: 'Authenticate to Google Cloud'
  #       uses: 'google-github-actions/auth@f112390a2df9932162083945e46d439060d66ec2' # google-github-actions/auth@v2
  #       with:
  #         workload_identity_provider: '${{ env.WORKLOAD_IDENTITY_PROVIDER }}'

  #     # BEGIN - Docker auth and build
  #     #
  #     # If you already have a container image, you can omit these steps.
  #     - name: 'Docker Auth'
  #       uses: 'docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567' # docker/login-action@v3
  #       with:
  #         username: 'oauth2accesstoken'
  #         password: '${{ steps.auth.outputs.auth_token }}'
  #         registry: '${{ env.REGION }}-docker.pkg.dev'

  #     - name: 'Build and Push Container'
  #       run: |-
  #         DOCKER_TAG="$${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}"
  #         docker build --tag "${DOCKER_TAG}" .
  #         docker push "${DOCKER_TAG}"
  #     - name: 'Deploy to Cloud Run'

  #       # END - Docker auth and build

  #       uses: 'google-github-actions/deploy-cloudrun@33553064113a37d688aa6937bacbdc481580be17' # google-github-actions/deploy-cloudrun@v2
  #       with:
  #         service: '${{ env.SERVICE }}'
  #         region: '${{ env.REGION }}'
  #         # NOTE: If using a pre-built image, update the image name below:

  #         image: '${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}:${{ github.sha }}'
  #     # If required, use the Cloud Run URL output in later steps
  #     - name: 'Show output'
  #       run: |2-

  #         echo ${{ steps.deploy.outputs.url }}
